/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f351d81a-9968-40cc-87ff-53bb433b3ca2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_skkh3monp",
    "aws_user_pools_web_client_id": "2p0l7o2lcnst4g39v9ktomaafp",
    "oauth": {}
};


export default awsmobile;
